name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # update setiap hari jam 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Set Git config agar commit muncul di contribution graph
      - name: Set Git Config
        run: |
          git config user.name "0xzhara"
          git config user.email "122523974+0xzhara@users.noreply.github.com"

      # 3️⃣ Generate snake animation
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: 0xzhara
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 4️⃣ Push generated snake to branch output atas nama kamu
      - name: Push snake animation
        run: |
          git add dist/*
          git commit -m "Update contribution snake [ci skip]" || echo "No changes to commit"
          git push https://0xzhara:${{ secrets.GH_PAT }}@github.com/0xzhara/0xzhara.git output
